### ISSUE TITLE
Issue with MultiPulse_varyCurrent_FeatureExtract

### ISSUE THREAD

**Issue by agnsinha99** [SchwartzNU/DJ_schwartzlab#4]
Error using fit>iFit
Inf computed by model function, fitting cannot continue.
Try using or tightening upper and lower bounds on coefficients.

Error in fit (line 116)
[fitobj, goodness, output, convmsg] = iFit( xdatain, ydatain, fittypeobj, ...

Error in MultiPulse_varyCurrent_FeatureExtract (line 175)
            f = fit([time_in_s(start_time:end_time)]', hyper_Vm(start_time:end_time,...

Error in sln_results.get (line 38)
    Rnew = eval(sprintf('%s(missing_results);', func_name));

Error in DataGrouper/RunanalysisButtonPushed (line 1822)
                R = sln_results.get(analysis_name,data_group,data_level,true);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by agnsinha99** [comment]
> Error using fit>iFit Inf computed by model function, fitting cannot continue. Try using or tightening upper and lower bounds on coefficients.
> 
> Error in fit (line 116) [fitobj, goodness, output, convmsg] = iFit( xdatain, ydatain, fittypeobj, ...
> 
> Error in MultiPulse_varyCurrent_FeatureExtract (line 175) f = fit([time_in_s(start_time:end_time)]', hyper_Vm(start_time:end_time,...
> 
> Error in sln_results.get (line 38) Rnew = eval(sprintf('%s(missing_results);', func_name));
> 
> Error in DataGrouper/RunanalysisButtonPushed (line 1822) R = sln_results.get(analysis_name,data_group,data_level,true);
> 
> Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171) callback(appOrUserComponent, event);
> 
> Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62) newCallback = @(source, event)executeCallback(ams, ...
> 
> Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback Error while evaluating Button PrivateButtonPushedFcn.

Example of cell with this issue: Cell 070323Ac9

**Comment by trungtranle** [comment]
Closes
